### ISSUE TITLE
Use Nuxt

### ISSUE THREAD

**Issue by imithu** [socketio/socket.io-admin-ui#14]
use nuxt (vue  based framework) instead  of vue

**Comment by imithu** [comment]
If you need help please let me know, I will work on the nuxt framework for socket.io-admin-ui.

**Comment by darrachequesne** [comment]
@imithu sure, please do! Could you please detail what the advantages are?

**Comment by imithu** [comment]
[YouTube:  Why use Nuxt.js? | 7 Problems you can avoid by using Nuxt.js for your next Vue app](https://youtu.be/7ITypVi-qRY)


Please watch this video.
Let me know if you want to go with the nuxtjs.


> Replay: @darrachequesne 
> @imithu sure, please do! Could you please detail what the advantages are?

**Comment by imithu** [comment]
You are most welcome.
