### ISSUE TITLE
xhr poll error when connecting with deployed server

### ISSUE THREAD

**Issue by MBEDevelopmentTeam** [socketio/socket.io-admin-ui#21]
when i try to connect my server from localhost it works and connects with admin UI but when i deployed it on some shared hosting its working fine with the android and react js apps but not connecting with the ADMIN UI of socket it shows the xhr poll error when i want to connect

**Comment by darrachequesne** [comment]
Hi! Any error in the console? Maybe related to CORS?

**Comment by MBEDevelopmentTeam** [comment]
not any sir i have allowed "*" and also the admin ui url so same code works at localhost but not after deployment

**Comment by darrachequesne** [comment]
That's weird indeed. Could you please check if there is any error logged in the console? What is the response body of the HTTP request?

See also: https://socket.io/docs/v4/troubleshooting-connection-issues/

**Comment by navxio** [comment]
same issue.. trying to deploy on heroku.
Tried with multiple namespaces, the server logs say 404..

**Comment by navxio** [comment]
@MBEDevelopmentTeam using `cors: ['https://admin.socket.io']` in place of `cors: ['*']` fixed it for me. Hope it helps

**Comment by darrachequesne** [comment]
@navxio awesome, thanks for the update 👍

Closing this, as the initial issue was certainly related to CORS.

Reference: https://socket.io/docs/v4/handling-cors/
