### ISSUE TITLE
Kills the performance of Socket.io Server

### ISSUE THREAD

**Issue by vishwassingh47** [socketio/socket.io-admin-ui#23]
My socket server can handle 10K connection easily.

But when i configured the admin ui ,with `namespaceName` as "/", socket server can handle max 1K connection and connections starts disconnecting.
`instrument(io, {
    auth: false,
    namespaceName:'/
});`

Have tested it multiple times.

But if i keep the namespaceName to 'admin' or 'someThingButNot/', it works fine.

`instrument(io, {
    auth: false,
    namespaceName:'adminBro'
});`

**Comment by darrachequesne** [comment]
That might be related to https://github.com/socketio/socket.io-admin-ui/issues/22.

That being said, I don't think using the main namespace is a good idea, as all modifications will now be broadcast to all your connected users, not only the admin users.
