### ISSUE TITLE
How to use it with redis Adapter?

### ISSUE THREAD

**Issue by jayd36** [socketio/socket.io-admin-ui#24]
If we have multiple servers running on different ports and those attached with Redis Adapter, how can we show the combined view of all the servers at the same page in admin UI?

**Comment by darrachequesne** [comment]
You should be able to see all servers in the UI. Isn't that the case?

**Comment by jayd36** [comment]
I can see only 1 server, however, I have created 8 different servers in fork mode using pm2.
The client connection count is correct, however the server count showing only 1.

**Comment by darrachequesne** [comment]
> If you have several Socket.IO servers on the same machine, you'll need to give them a distinct ID:

```js
instrument(io, {
  serverId: `${require("os").hostname()}#${process.pid}`
});
```

Documentation:
- https://github.com/socketio/socket.io-admin-ui#serverid
- https://socket.io/docs/v4/admin-ui/#serverid
