### ISSUE TITLE
No data but seems to be logged in correctly

### ISSUE THREAD

**Issue by HugoGresse** [socketio/socket.io-admin-ui#26]
Hi there, 
I wanted to use this nice admin UI but had some issue.  The status is "Connected" in green, but I have literally no data, no client, no server... everything is 0

What I check:
- correct bcrypt hash: I made sure to use node.bcrypt.js to hash the pwd
- the login POST request response is "ok" 
- not linked to adblock, same on chrome and firefox

Cf the screenshot: 
![Capture d’écran 2021-09-06 à 23 02 38](https://user-images.githubusercontent.com/662377/132260384-513d46e4-a09c-4d7d-beb6-77e612a5d6ce.png)

And the WS request transfer the following: 
![Capture d’écran 2021-09-06 à 23 05 13](https://user-images.githubusercontent.com/662377/132260469-2a7442e6-7b84-472a-b043-e5dc50358e9e.png)

I've installed : 
`
        "@socket.io/admin-ui": "^0.2.0",
        "socket.io": "^4.1.1",
        "socket.io-client": "^4.1.1",
`

and I'm using node 16. 

Is there anything I'm missing?

**Comment by darrachequesne** [comment]
I think that's because you used `https://s.bataille.ovh` instead of `https://s.bataille.ovh/admin`, so you're connected to the main namespace. Could you please check?

**Comment by HugoGresse** [comment]
Haaaaaaaaaaa dammit, thanks for the quick answer! 
And it was stated in the documentation also..... 😅
