### ISSUE TITLE
Admin UI not connecting with parser option ( socket.io-msgpack-parser )

### ISSUE THREAD

**Issue by merndev** [socketio/socket.io-admin-ui#28]
When the parser option is passed, the admin UI is not conneting.

socket.io-msgpack-parser : 3.0.1
socket.io 4.2.0
socket.io-client 4.2.0
Trying to access admin UI through https://admin.socket.io/

**Comment by sasa10g** [comment]
Same here, won't work with any custom parser.
It would be great to have it.

**Comment by darrachequesne** [comment]
@sasa10g working with any arbitrary parser seems difficult (well, we could `eval` the code of the parser provided by the user, but I'm not sure that's a good idea).

We should be able to include the msgpack parser though :+1:

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-admin-ui/commit/4359536a4b9c09395c52ac7e983123f02043ac5c:

![Screenshot from 2022-05-03 07-39-21](https://user-images.githubusercontent.com/13031701/166408870-5cecae08-bedb-434b-af1c-cfcfedf1d4b8.png)
