### ISSUE TITLE
[UX] Header is not compatible for mobile devices

### ISSUE THREAD

**Issue by dkonopka** [socketio/socket.io-admin-ui#29]
Take a look at the header, there is a field for improvement (it should be wrapped to the next row):

# Current view
![Screenshot 2021-09-30 at 07 27 55](https://user-images.githubusercontent.com/10219857/135392739-5e0e169a-ae9a-4f61-b443-aa1875033e98.png)

# Proposal
<img width="716" alt="Screenshot 2021-09-30 at 07 33 50" src="https://user-images.githubusercontent.com/10219857/135393250-a59e64db-77e5-46a6-99c7-0e8e6ca71992.png">

**Comment by darrachequesne** [comment]
Merged in https://github.com/socketio/socket.io-admin-ui/commit/62e146709f1b4ceee86b6c9d414d0538b2991833. Thanks a lot :+1:
