### ISSUE TITLE
Retrieve "socket.data" from sockets

### ISSUE THREAD

**Issue by y4my4my4m** [socketio/socket.io-admin-ui#32]
https://github.com/socketio/socket.io-admin-ui/blob/main/lib/index.ts#L338-L366

Why is data not included? All custom data are added to `socket.data` since v4 I believe.

**Comment by y4my4my4m** [comment]
@darrachequesne 
I've opened a PR on this matter a while back but I'm stomped, can't seem to make it work.

Could you take a look?
https://github.com/socketio/socket.io-admin-ui/pull/34

Cheers

**Comment by darrachequesne** [comment]
This was implemented in https://github.com/socketio/socket.io-admin-ui/commit/3773fe4b1cbf2206708e1f21ce65f430a522527f and included in version `0.3.0`:

![Peek 2022-05-03 07-44](https://user-images.githubusercontent.com/13031701/166409269-7ec73dfc-7f5c-44f9-aafa-6af2daa0f8b9.gif)
