### ISSUE TITLE
Won't connect on ec2 amazon instance

### ISSUE THREAD

**Issue by wuilmerj24** [socketio/socket.io-admin-ui#33]
I am trying to connect to my server on an amazon ec2 instance and it won't connect. But locally if it connects.

**Comment by darrachequesne** [comment]
For future readers:

You won't be able to reach a server without SSL from the admin UI, which is served from an HTTPS url: https://admin.socket.io/

But since SSL certs are more or less free these days, I don't think there's much we can do. Please reopen if needed!
