### ISSUE TITLE
Support relative links in index.html

### ISSUE THREAD

**Issue by Thomas-1985** [socketio/socket.io-admin-ui#41]
Hi

I am serving the ui files in my Express app via
`app.use(express.static(path.resolve('public')));`

in a subdirectory called `socket.ui`. With the index.html provided this doesn't work as the links to css, webpack etc. start with `/` 

If you could change it to relative links, this should work.

Best,
Thomas

**Comment by darrachequesne** [comment]
That sounds reasonable :+1:

**Comment by darrachequesne** [comment]
This was implemented in https://github.com/socketio/socket.io-admin-ui/commit/fdec2ce17bf7cad77a04e8eef42a26104b6a05b8, included in version `0.4.0`.

Have a great day!
