### ISSUE TITLE
How can I open this menu?

### ISSUE THREAD

**Issue by jtapeg** [socketio/socket.io-admin-ui#43]
![image](https://user-images.githubusercontent.com/52453013/174893448-644ae994-e6ec-4156-b7f6-33d601f03997.png)

**Comment by darrachequesne** [comment]
Hi! The navigation drawer was indeed not properly displayed, this should be fixed now: https://github.com/socketio/socket.io-admin-ui/commit/77ee0683185aceababc4439a3a945e273d547944
