### ISSUE TITLE
Login issue on multi-server setup (xhr post error, Session ID unknown)

### ISSUE THREAD

**Issue by Dissfall** [socketio/socket.io-admin-ui#5]
Hi! I have a problem logging into the admin panel when I have multiple servers in a load-balancing group.

Му `instrument` configuration looks like:
```typescript
instrument(io, {
  readonly: true,
  auth: false,
  store: new RedisStore(redisClient)}
})
```
My `socket.io` configuration:
```JSON
{
    "allowEIO3": true,
    "transports": ["polling", "websocket"],
    "cors": {
        "origin": ["https://admin.socket.io"]
    }
}
```

When I try to connect to application with single server in load-balancing group everything works fine and I can see the connection metadata in Redis.

But when I try to connect to application with multiple servers I get error `xhr post error`

Request:
```
POST /socket.io/?EIO=4&transport=polling&t=NayhWmL&sid=jlBhx1IfS1dZEpWOAANq HTTP/2
Host: develop.myserver.app:3001
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-type: text/plain;charset=UTF-8
Content-Length: 1
Origin: https://admin.socket.io
Connection: keep-alive
Referer: https://admin.socket.io/
TE: Trailers
```

Response:
```
HTTP/2 400 Bad Request
date: Wed, 05 May 2021 13:18:29 GMT
content-type: application/json
set-cookie: AWSALB=/3ZFJ1ljYdZVVpueuztmZeLiyAzPiZ+m9iRf0L8SZLZw2Y44fUk6E5IThvk0+5Z+FurdStn9oIWXtqtGWB5ibYLcEU6OlqOWcMC75zpmSks+cT1WNg7YVcEHe; Expires=Wed, 12 May 2021 13:18:29 GMT; Path=/
set-cookie: AWSALBCORS=/3ZFJ1ljYdZVVpueuztmZeLiyAzPiZ+m9iRf0L8SZw2Y44fUk6E5IThvk0+5Z+FurdStn9oIWXtqtGWB5ibYLcEU6OlqOWcMCh5W75zpmSks+cT1WNg7YVcEHe; Expires=Wed, 12 May 2021 13:18:29 GMT; Path=/; SameSite=None; Secure
access-control-allow-origin: https://admin.socket.io
vary: Origin
X-Firefox-Spdy: h2
```
Response body:
```JSON
{"code":1,"message":"Session ID unknown"}
```

**Comment by darrachequesne** [comment]
Did you enable sticky-session?

Reference: https://socket.io/docs/v4/using-multiple-nodes/

**Comment by Dissfall** [comment]
@darrachequesne thanks for responding!

Yes, sticky-session is set in my environment.

That is how my application load balancer setup looks:
<img width="1000" alt="Снимок экрана 2021-05-06 в 11 11 57" src="https://user-images.githubusercontent.com/28986337/117308603-62b9dd80-ae8a-11eb-9612-9b7bdfe84d10.png">
<img width="493" alt="Снимок экрана 2021-05-06 в 11 15 08" src="https://user-images.githubusercontent.com/28986337/117308638-69e0eb80-ae8a-11eb-9eb9-af7662a7ae65.png">

**Comment by darrachequesne** [comment]
Arf, I think I found the problem, the client must be initialized with `withCredentials: true`, in order to send the `AWSALBCORS` cookie (since we are in a CORS situation).

**Comment by Dissfall** [comment]
I forgot to say I am using socket.io version 3

Now I set `credentials: true` in `cors` like that:
```typescript
const options: Partial<ServerOptions> = {
  allowEIO3: true,
  transports: TRANSPORTS,
  pingInterval: PING_INTERVAL,
  pingTimeout: PING_TIMEOUT,
  cors: {
    origin: ['https://admin.socket.io'],
    credentials: true
  }
};
```
But nothing changes 😔

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/socket.io-admin-ui/commit/51fac0aeb8ae2cfb6fa319525de9b1208aada463.

Could you please check?

**Comment by aryaman-titan** [comment]
There are few cases when I want the server to connect from various origins (for example in a chrome extension), and hence I have to set "*" in the `origin` of `cors` options, but then the connection is disallowed due to CORS policy. In such cases, do I have to rebuild the admin UI with `withCredentials: false` and then self-host it, or is there any way around it? @darrachequesne

**Comment by darrachequesne** [comment]
@aryaman-titan in that case, I think you should be able to provide a noop function to the `cors` module:

```js
const io = new Server(httpServer, {
  cors: {
    origin: function (origin, cb) {
      cb(null, true); // WARNING: all origins are allowed
    },
    credentials: true
  }
});
```

Reference: https://www.npmjs.com/package/cors

**Comment by aryaman-titan** [comment]
Thanks @darrachequesne! That works 👍🏻
