### ISSUE TITLE
netty-socketio can use admin-ui ?

### ISSUE THREAD

**Issue by ZhangWeiHelloWorld** [socketio/socket.io-admin-ui#57]
my project use netty-socketio 1.7.22 ,java project. how to use admin-ui for my java project ?

**Comment by darrachequesne** [comment]
Hi! Yes, this should be feasible, one just needs to implement the server-side logic [here](https://github.com/socketio/socket.io-admin-ui/blob/develop/lib/index.ts) in Java.
