### ISSUE TITLE
Joining namespace room is impossible

### ISSUE THREAD

**Issue by dkonopka** [socketio/socket.io-admin-ui#73]
Suddenly, without any architecture changes, there is no way to join socket namespace room, do you have any idea why?

### Joining /admin name space works properly:

![Screenshot 2023-09-07 at 13 14 02](https://github.com/socketio/socket.io-admin-ui/assets/10219857/cca637df-7016-466f-8d19-7eb83c86444e)

### Changing name space to /app

Popup is closing with showing before an error like ~200ms and later on displaying no data (no rooms, sockets)

![Screenshot 2023-09-07 at 13 15 40](https://github.com/socketio/socket.io-admin-ui/assets/10219857/fce6389a-9875-4706-9b21-6ff0a882d4bc)

### package.json

```
"@socket.io/admin-ui": "^0.5.1",
"socket.io": "^4.2.0",
"socket.io-client": "^4.2.0",
```

**Comment by darrachequesne** [comment]
Hi! That's weird, there hasn't been a recent update.

Have you found the culprit?

**Comment by dkonopka** [comment]
@darrachequesne unfortunately not, still the same situation, I didn't update socket.io version or even anything else.

![Screenshot 2023-09-20 at 20 45 07](https://github.com/socketio/socket.io-admin-ui/assets/10219857/77ddd2ec-94b7-47bb-a0bc-ece9af1a8e1f)

entering `/app` room is returning an error and empty data

**Comment by dkonopka** [comment]
@darrachequesne maybe you have some idea how to debug it, why there is `io client disconnect` error while trying to join `/app` namespace where `/admin` works properly?

**Comment by dkonopka** [comment]
Issue solved, I had `mode: production` and it makes rooms invisible :)
