### ISSUE TITLE
sass library problem

### ISSUE THREAD

**Issue by sercangoger** [socketio/socket.io-admin-ui#78]
No matter what I did, I could not solve the library problem. A version problem with the sass library.

**
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($timeline-divider-width, 2) or calc($timeline-divider-width / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
89 │         max-width: calc(#{$timeline-divider-center} - #{$timeline-divider-width / 2})
   │                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VTimeline/VTimeline.sass 89:57  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-($slider-thumb-size - 4), 2) or calc(-1 * ($slider-thumb-size - 4) / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
254 │     left: -($slider-thumb-size - 4) / 2
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/vuetify/src/components/VSlider/VSlider.sass 254:11  root stylesheet

WARNING: 6 repetitive deprecation warnings omitted.

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$toolbar-btn-icon-size, 4) or calc(-1 * $toolbar-btn-icon-size / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
37 │         margin-left: -$toolbar-btn-icon-size / 4
   │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 37:22  @content
    node_modules/vuetify/src/styles/tools/_rtl.sass 7:5               ltr()
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 36:7   root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$toolbar-btn-icon-size, 4) or calc(-1 * $toolbar-btn-icon-size / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
40 │         margin-right: -$toolbar-btn-icon-size / 4
   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 40:23  @content
    node_modules/vuetify/src/styles/tools/_rtl.sass 3:5               rtl()
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 39:7   root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$toolbar-btn-icon-size, 4) or calc(-1 * $toolbar-btn-icon-size / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
51 │         margin-right: -$toolbar-btn-icon-size / 4
   │                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 51:23  @content
    node_modules/vuetify/src/styles/tools/_rtl.sass 7:5               ltr()
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 50:7   root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$toolbar-btn-icon-size, 4) or calc(-1 * $toolbar-btn-icon-size / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
54 │         margin-left: -$toolbar-btn-icon-size / 4
   │                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 54:22  @content
    node_modules/vuetify/src/styles/tools/_rtl.sass 3:5               rtl()
    node_modules/vuetify/src/components/VToolbar/VToolbar.sass 53:7   root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(map-get($size, "height"), 2) or calc(map-get($size, "height") / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
202 │       border-radius: #{map-get($size, 'height') / 2}px
    │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/vuetify/src/components/VChip/VChip.sass 202:24  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($switch-track-inset-height, 2) or calc($switch-track-inset-height / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
116 │       top: calc(50% - #{$switch-track-inset-height / 2})
    │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/vuetify/src/components/VSwitch/VSwitch.sass 116:25  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($progress-linear-stream-border-width, 2) or calc($progress-linear-stream-border-width / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
113 │   top: calc(50% - #{$progress-linear-stream-border-width / 2})
    │                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/vuetify/src/components/VProgressLinear/VProgressLinear.sass 113:21  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(-$banner-y-padding, 2) or calc(-1 * $banner-y-padding / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
26 │   margin-bottom: -$banner-y-padding / 2
   │                  ^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VBanner/VBanner.sass 26:18  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($banner-y-padding, 2) or calc($banner-y-padding / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
85 │     padding-top: $banner-y-padding / 2
   │                  ^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VBanner/VBanner.sass 85:18  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($banner-y-padding, 2) or calc($banner-y-padding / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
86 │     padding-bottom: $banner-y-padding / 2
   │                     ^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules/vuetify/src/components/VBanner/VBanner.sass 86:21  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($alert-padding, 2) or calc($alert-padding / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
141 │   padding-top: $alert-padding / 2
    │                ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/vuetify/src/components/VAlert/VAlert.sass 141:16  root stylesheet

DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($alert-padding, 2) or calc($alert-padding / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
142 │   padding-bottom: $alert-padding / 2
    │                   ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/vuetify/src/components/VAlert/VAlert.sass 142:19  root stylesheet
**

**Comment by sercangoger** [comment]
I need to migrate for this error but I can't do it.



RUN npm install
RUN npm install -g sass-migrator
#RUN sass-migrator division node_modules/quasar/src/css/**/*.sass
#RUN sass-migrator division **/*.scss
RUN npm install -D rollup-plugin-sass-migrator sass-migrator

**Comment by serhatoral** [comment]
@sercangoger  This project does not support Node versions higher than 14.21.3 and is not compatible with higher versions of sass library. You should downgride Node version on your computer. You can easily do this by using nvm as fallows;

```
nvm install 14.21.3
nvm use 14.21.3
nvm list
```
Finally, you can run the project using `npm install` and `npm run serve`

**Comment by ghost** [comment]
https://github.com/socketio/socket.io-admin-ui/issues/83

fixed.

**Comment by sercangoger** [comment]
worked for me too fixed.
