### ISSUE TITLE
Admin UI doesen't seem to work with auth

### ISSUE THREAD

**Issue by paoloricciuti** [socketio/socket.io-admin-ui#9]
If i try to set auth to false it all works as a charm but as soon as i set up auth it stop working. In particoulpar:

- If i try to connect to https://myserver.com/admin with the correct credentials it gives me "Invalid credetials"
- If i try to connect to https://myserver.com with the correct credentials it let me in but i have no data in the admin ui

I've also tried to specify the namespace of /admin with the auth being set but it still gives me invalid credentials.

I'm using NEXT.js setting up the handler for next in an express server (in the same place i've also set up socket.io.

**Comment by darrachequesne** [comment]
Could you please check if your encrypted password is valid?

```
$ node
> require("bcrypt").compareSync("changeit", "$2b$10$heqvAkYMez.Va6Et2uXInOnkCT6/uQj1brkrbyG3LpopDklcq7ZOS")
true
```

It seems hashes starting with `$2y$` are not supported by the `bcrypt` package: https://github.com/kelektiv/node.bcrypt.js/issues/849

**Comment by paoloricciuti** [comment]
> Could you please check if your encrypted password is valid?
> 
> ```
> $ node
> > require("bcrypt").compareSync("changeit", "$2b$10$heqvAkYMez.Va6Et2uXInOnkCT6/uQj1brkrbyG3LpopDklcq7ZOS")
> true
> ```
> 
> It seems hashes starting with `$2y$` are not supported by the `bcrypt` package: [kelektiv/node.bcrypt.js#849](https://github.com/kelektiv/node.bcrypt.js/issues/849)
> 
> More information here: https://stackoverflow.com/a/36225192/5138796

I think this was the issue...maybe this needs to be added to the documentation. To hash my password i used the first result on google and i think a lot of people might run into this issue.

Thanks for the suggestion!

**Comment by darrachequesne** [comment]
This totally needs to be added to the documentation :+1: here we go: https://github.com/socketio/socket.io-admin-ui/commit/5d92994bca4bab8cbd5f974cbe9506f9a976c1c5

Thanks!
